# Константы для ингредиентов
MAX_LENGTH_INGREDIENT_NAME = 128
MAX_LENGTH_INGREDIENT_MEASUREMENT_UNIT = 64

# Константы для рецептов
MAX_LENGTH_RECIPE_NAME = 256
MIN_COOKING_TIME_VALUE = 1
MIN_AMOUNT_VALUE = 1

# Константы для пользователей
USER_FIRST_NAME_MAX_LENGTH = 150
USER_LAST_NAME_MAX_LENGTH = 150
USER_EMAIL_MAX_LENGTH = 254
USER_USERNAME_MAX_LENGTH = 150
USER_USERNAME_REGEX = r'^[\w.@+-]+\Z'
USER_AVATAR_UPLOAD_TO = 'avatars/'

# Константы для base62
BASE62_ALPHABET = (
    "0123456789abcdefghijklmnopqrstuvwxyz"
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
)
BASE62_DIVIDER = 62
